apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-flask
  labels:
    app: hello-flask

spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-flask
  template:
    metadata:
      labels:
        app: hello-flask
    spec:
      containers:
        - name: hello-flask
          image: raw101/web101
          ports:
            - containerPort: 8080


---

apiVersion: v1
kind: Service
metadata:
  name: hello-flask-service
  labels:
    app: hello-flask
spec:
  type: NodePort
  selector:
    app: hello-flask
  ports:
  - name: http
    protocol: TCP
    port: 3000
    targetPort: 8080
