name: kubernetes deployment


on:
  push:
    branches:
      - main

env:
  KUBE_CONFIG_DATA:  ${{ secrets.KUBE_CONFIG_DATA }}

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy app
        uses: actions-hub/kubectl@master
        with:
          args: apply -f deploymentservice.yml
        
