name: kubernetes deployment


on:
  push:
    branches:
      - main

env:
  KUBE_CONFIG:  ${{ secrets.KUBE_CONFIG }}

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: check 
        run: echo hello linux
  
        

      # - name: Deploy App(Deployment)
      #   uses: actions-hub/kubectl@master
      #   with:
      #     args: apply -f deploymentservice.yml
        
